package io.epopeia.authorization.enums;

public enum ECardInfo {
	CARD_INFO,
	CARD_ID,
	CARD_BALANCE,
	CARD_FUNCTION,
	CARD_STATUS,
	CARD_SITUATION,
	CARD_EXPIRY_DATE,
	CARD_CHANNEL_ID,
	ACCOUNT_ID,
	ACCOUNT_STATUS,
	ACCOUNT_SITUATION,
	GROUP_RESTRICTION_ID,
	MODALITY_ID,
	PRODUCT_ID,
	BRAND_ID
}
