package io.epopeia.authorization.enums;

/**
 * Definicao dos tipos de transacoes a serem processados
 * pela procedure InsereTransacao.
 * 
 * Essa eh uma definicao que podera ser unificada no futuro
 * com os tipos de transacao da autorizadora.
 * 
 * @author Fernando Amaral
 */
public enum ETipoTransacao {
	CARGA_PRE_PAGO,
	COMPRA_CREDITO_A_VISTA,
	TARIFA_DE_SAQUE,
	TAXA_DE_SERVICO,
	TAXA_DE_FRETE,
	TAXA_DE_REEMISSAO,
	TAXA_DE_REATIVACAO,
	COMPRA_DEBITO,
	COMPRA_CREDITO_PARCELADO_LOJISTA,
	COMPRA_CREDITO_PARCELADO_EMISSOR,
	TRANSFERENCIA_DE_SALDO_A_CREDITO,
	TRANSFERENCIA_DE_SALDO_A_DEBITO,
	SAQUE,
	TARIFA_CONSULTA_SALDO,
	ESTORNO,
	ESTORNO_CARGA,
	CARGA_PEC,
	TARIFA_TRANSACAO_INTERNACIONAL,
	TARIFA_EMISSAO,
	TARIFA_RECARGA_PEC,
	RECEBIMENTO_REC,
	TARIFA_RECEBIMENTO_REC,
	COMPRA_AGRO_CUSTEIO,
	COMPRA_AGRO_INVESTIMENTO,
	ESTORNO_AGRO_CUSTEIO,
	ESTORNO_AGRO_INVESTIMENTO,
	ESTORNO_COMPRA_AGRO_CUSTEIO,
	ESTORNO_COMPRA_AGRO_INVESTIMENTO,
	CARGA_AGRO_CUSTEIO,
	CARGA_AGRO_INVESTIMENTO,
	ESTORNO_CARGA_AGRO_CUSTEIO,
	ESTORNO_CARGA_AGRO_INVESTIMENTO,
	TAXA_BNDES,
	DEVOLUCAO_SALDO_COMUM
}
